#!/bin/bash

log4netversion=$(grep  "log4net, Version" log4net.Ext.Json.nuget.csproj | sed -re 's/.* Version=([0-9.]*).*/\1/')
log4netnuget=$(grep "log4net" packages.config | sed -re 's/.* version="([^"]*)".*/\1/')
gitcommit=$(git rev-parse HEAD)
gitstatus=$(git status -s)
builddate=$(date +%Y-%m-%d)

if [[ ! -z $gitstatus ]] ; then
	echo "Working dir not in order, quitting:"
	echo "$gitstatus"
	exit 1
fi

build () {
	netverson="$1"
	profile="$2"

	conf="Built on $builddate against log4net v $log4netversion nuget v $log4netnuget"
	conf="$conf with .net framework $netversion $profile"
	conf="$conf off of git commit $gitcommit"

	sed -f - -i Properties/AssemblyInfo.cs <<-EOSED
		s/AssemblyConfiguration("[^"]*")/AssemblyConfiguration("$conf")/
		s/AssemblyFileVersion("[^"]*")/AssemblyFileVersion("$log4netversion")/
	EOSED

	xbuild /verbosity:quiet /nologo \
		/p:TargetFrameworkVersion="$netversion" \
		/p:TargetFrameworkProfile="$profile" \
		/p:Configuration="Release" \
		log4net.Ext.Json.nuget.csproj
}

build "v2.0"
build "v3.0"
build "v3.5"
build "v3.5" "Client"
build "v4.0"
build "v4.0" "Client"
build "v4.5"

sed -rf - -i log4net.Ext.Json.nuget.nuspec <<-EOSED
	s/\d\d\d\d-\d\d-\d\d/$builddate/
	s/[a-fA-F0-9]{8,64}/$gitcommit/
	s/<version>[0-9.]+<\/version>/<version>$log4netversion<\/version>/
	s/id="log4net" version="[0-9.]+"/id="log4net" version="$log4netnuget"/
EOSED

mono ../lib/nuget.exe pack log4net.Ext.Json.nuget.nuspec
